export const copilotLabels = {
  en: {
    heading: 'AI copilot',
    subheading: 'Explain this risk',
    explain: 'Explain risk',
    loading: 'Generating explanation…',
    language: 'Language',
    audience: 'Audience',
    english: 'English',
    hindi: 'Hindi',
    authority: 'Authority',
    resident: 'Resident',
    riskFactors: 'Risk factors',
    communityActions: 'Community actions',
    geminiSource: 'Gemini',
    offlineSource: 'Offline template',
    copyAdvisory: 'Copy advisory',
    copied: 'Advisory copied',
    copyFailed: 'Could not copy the advisory.',
    disclaimer: 'General precautions only, not medical advice.',
  },
  hi: {
    heading: 'AI सहायक',
    subheading: 'इस जोखिम को समझें',
    explain: 'जोखिम समझाएँ',
    loading: 'जानकारी तैयार हो रही है…',
    language: 'भाषा',
    audience: 'पाठक',
    english: 'अंग्रेज़ी',
    hindi: 'हिंदी',
    authority: 'अधिकारी',
    resident: 'निवासी',
    riskFactors: 'जोखिम के कारण',
    communityActions: 'समुदाय के लिए कदम',
    geminiSource: 'Gemini',
    offlineSource: 'ऑफ़लाइन टेम्पलेट',
    copyAdvisory: 'सलाह कॉपी करें',
    copied: 'सलाह कॉपी हो गई',
    copyFailed: 'सलाह कॉपी नहीं हो सकी।',
    disclaimer: 'General precautions only, not medical advice.',
  },
};
